/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/toy.gltf 
Author: Jamessmartguy (https://sketchfab.com/skybaca1985)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/woody-toy-story-f88d8092b28d4a5d9e3cc4db99ca3aff
Title: Woody Toy Story
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Toy(props) {
  const { nodes, materials } = useGLTF("/toy.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.Material_10}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.Material_11}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.Material_12}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.Material_14}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.Material_7}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials.Material_9}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/toy.gltf");
